{% set name = "autoregistry" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoregistry-{{ version }}.tar.gz
  sha256: b4d9ab95a64a2cc71eeb100367175f22241785bc0c12462f2591c901dfb5b1cb

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.1
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - autoregistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BrianPugh/autoregistry
  summary: Automatic registry design-pattern for mapping names to functionality.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
