{% set name = "autoregistry" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoregistry-{{ version }}.tar.gz
  sha256: 8ef98737da4fb2cbb1b70e7408a4e54eebfafc1b785d745f6737dd40479100e5

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry >=1.2.0
    - poetry-dynamic-versioning-plugin
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0

test:
  imports:
    - autoregistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BrianPugh/autoregistry
  summary: Automatic registry design-pattern for mapping names to functionality.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
