{% set name = "autoregistry" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autoregistry-{{ version }}.tar.gz
  sha256: 22212c2c53b938816e8579b6766a4b3198b66eda92609eaab1cb141fc859f1be

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=0.21.5
    - python >=3.8
  run:
    - python >=3.8

test:
  imports:
    - autoregistry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BrianPugh/autoregistry
  summary: Automatic registry design-pattern for mapping names to functionality.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
